# Generated by Django 5.0.6 on 2024-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_preetynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preetynum',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格/元'),
        ),
    ]
