# Generated by Django 3.2.25 on 2024-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('num', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=64, upload_to='', verbose_name='Logo')),
            ],
        ),
    ]
